### ISSUE TITLE
bioawk parsing is wrong with this bison version

### ISSUE THREAD

**Issue by janxkoci** [conda-forge/bison-feedstock#22]
Issue:
I tried to use bioawk on a few servers. I first installed it on one server (OpenSUSE) from bioconda channel, but the parsing was wrong (see https://github.com/lh3/bioawk/issues/34). Than I used git version on several servers (Gentoo and CentOS) and it worked fine except on the first OpenSUSE server. On this server I had a problem compiling the git version (missing `yacc`) so I did `conda install bison` and then I could compile bioawk just fine. However after compiling the new git bioawk gives the same wrong parsing results as the bioconda version.

To summarise: bioawk works with git version correctly, if there was already `yacc` present on the system. If it wasn't present and I installed it from conda forge using bison package, it doesn't work correctly.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/koci/miniconda3/envs/bioawk:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
bioawk                    1.0                  h84994c4_4    bioconda
bison                     3.4                  he1b5a44_1    conda-forge
flex                      2.6.4             he1b5a44_1004    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
m4                        1.4.18            h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : bioawk
    active env location : /home/koci/miniconda3/envs/bioawk
            shell level : 2
       user config file : /home/koci/.condarc
 populated config files : /home/koci/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /home/koci/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/koci/miniconda3/pkgs
                          /home/koci/.conda/pkgs
       envs directories : /home/koci/miniconda3/envs
                          /home/koci/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.3 Linux/4.1.15-8-default opensuse/42.1 glibc/2.19
                UID:GID : 1017:100
             netrc file : None
           offline mode : False

```
</details>

**Comment by jakirkham** [comment]
Is it possible `bioawk` is sensitive to the version of `bison`? If so, should this be constrained in that package somehow?

**Comment by janxkoci** [comment]
I have no idea, I'm just a user. Were there some parsing-related changes between versions?

**Comment by jakirkham** [comment]
Have you brought this up with the maintainers of `bioawk`? That is where I would start.

**Comment by janxkoci** [comment]
Yes, see the original post with the link to the reported issue. But because the issue only occurs if I install `bison` from `conda`, I decided to inform you as well.

**Comment by jakirkham** [comment]
Sorry I should have been more clear. Did you raise this with the bioconda maintainers?

**Comment by janxkoci** [comment]
Oh, no I didn't. However the issue occurs even if I install bioawk from git and only use bison to resolve missing dependency (see first post). So it doesn't seem like it's an issue with bioconda package.

**Comment by jakirkham** [comment]
Oh ok. Well that may be the case, but they may be more familiar with this tool and how it can be built. That info could be useful here

**Comment by janxkoci** [comment]
I forgot to close this after I found my issue was caused by my locale. Closing now.
