### ISSUE TITLE
Bison is not 100% relocatable?

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/bison-feedstock#7]
While building gstreamer 1.12.2, the build mysteriously failed with:
```
make[4]: Entering directory `/opt/conda/conda-bld/gstreamer_1516035349126/work/gst/parse'
/opt/conda/conda-bld/gstreamer_1516035349126/_build_env/bin/bison -d -v -ppriv_gst_parse_yy ./grammar.y -o grammar.tab.c && \
mv grammar.tab.c grammar.tab_tmp.c && \
echo '#ifdef HAVE_CONFIG_H' > grammar.tab_tmp2.c && \
echo '#include <config.h>' >> grammar.tab_tmp2.c && \
echo '#endif' >> grammar.tab_tmp2.c && \
cat grammar.tab_tmp.c >> grammar.tab_tmp2.c && \
rm grammar.tab_tmp.c && \
mv grammar.tab_tmp2.c grammar.tab.c
make[4]: *** [grammar.tab.h] Error 141
make[4]: Leaving directory `/opt/conda/conda-bld/gstreamer_1516035349126/work/gst/parse'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/opt/conda/conda-bld/gstreamer_1516035349126/work/gst'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/opt/conda/conda-bld/gstreamer_1516035349126/work/gst'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/conda/conda-bld/gstreamer_1516035349126/work'
make: *** [all] Error 2
```

On digging further, I found that bison couldn't find m4:
```
[pid 13041] execve("/opt/conda/conda-bld/bison_1515867734609/_build_env/bin/m4", ["/opt/conda/conda-bld/bison_15158"..., "--gnu", "-I", "/opt/conda/conda-bld/gstreamer_1"..., "/opt/conda/conda-bld/gstreamer_1"..., "-", "/opt/conda/conda-bld/gstreamer_1"..., "/opt/conda/conda-bld/gstreamer_1"...], [/* 26 vars */] <unfinished ...>
[pid 13040] <... close resumed> )       = 0
[pid 13041] <... execve resumed> )      = -1 ENOENT (No such file or directory)
```
Why is it looking inside `/opt/conda/conda-bld/bison_1515867734609` ? That directory doesn't exist!

I got around this by doing:
```
export M4=/opt/conda/conda-bld/gstreamer_1516043036525/_build_env/bin/m4
```

References:
- https://lists.yoctoproject.org/pipermail/poky/2012-January/007403.html
- https://www.mail-archive.com/gcc@gccsdk.riscos.info/msg02246.html
- https://github.com/Alexpux/MINGW-packages/issues/402

**Comment by pkgw** [comment]
I'm seeing this problem too, on linux-64, version `3.0.5 hfc679d8_1`.

**Comment by pkgw** [comment]
If nothing else, `m4` should be a runtime dependency of this package, which it isn't right now. It looks like the default path to the M4 executable is embedded in the `bison` executable with a compile-time C #define, so I'm not sure why the standard prefix-replacement technique isn't working here.

**Comment by nsoranzo** [comment]
I think I'm seeing the same issue in https://github.com/bioconda/bioconda-recipes/pull/11348 . From https://circleci.com/gh/bioconda/bioconda-recipes/29599 : 
```
bison --yacc -d  parser.y

make[1]: *** [y.tab.h] Broken pipe
```

**Comment by nehaljwani** [comment]
xref: https://github.com/AnacondaRecipes/bison-feedstock/commit/426854131b79dcdf8c930edbaaeb456a6e2b5bc2

**Comment by mingwandroid** [comment]
export `M4=m4` is the correct fix here.

**Comment by dakcarto** [comment]
@mingwandroid wrote:
> export `M4=m4` is the correct fix here.

Would this makes sense to be added to an activate/deactivate script, in this recipe?

`export M4=m4` worked for me as well.

**Comment by mingwandroid** [comment]
No.

**Comment by mingwandroid** [comment]
We avoid activate scripts unless there's a very very good reason to have them.

Setting one env var to workaround one braindead build system is not something I would entertain. Where does it end? Every package exporting FOO=$PREFIX/bin/foo? No thanks!

**Comment by pkgw** [comment]
I agree, but to be precise, this isn't a braindead build system. The bison binary that is being distributed contains a busted path somehow.

**Comment by mingwandroid** [comment]
You're welcome to your opinion. I disagree with it. Perhaps we talking at crossed purposes or I misunderstood? It's braindead for bison's build system to assume that baking fixed paths in binaries or scripts is acceptable in this day and age IMHO, and infecting *another* package (m4) with things such as activate scripts to work around such a problem is definitely not what we want to do here. What if a user has M4 set already? Same questions apply for any binary and any package.

**Comment by mingwandroid** [comment]
> The bison binary that is being distributed contains a busted path somehow

Did you miss this? https://github.com/conda-forge/bison-feedstock/issues/7#issuecomment-429637712

**Comment by mingwandroid** [comment]
To be clearer (hopefully) we don't want either package to have activate scripts. If bison is built with just the filenames for m4 instead of the full path, as we do on AD, then, provided people activate correctly things work just fine.

**Comment by pkgw** [comment]
Oh, I see. I thought you were talking about the build systems of package that were *using* bison, not bison itself. I could see arguments either way for what bison's build is doing, but clearly it isn't working for us.

We should get the patch alluded to in [#7](https://github.com/conda-forge/bison-feedstock/issues/7#issuecomment-429637712) into the conda-forge recipe! That should be a pretty trivial PR.
